import Navbar from './component/navbar'
import './global.css'


export const metadata = {
  title: "Create Next App",
   description: "Generated by create next app",
 };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body >
        <Navbar/>


        {/* <div className="navbar"> */}
          {/* <Link href={'./'}>Bosh sahifa</Link> */}
          {/* <Link href={'./about'}>About sahifa</Link> */}
          {/* <Link href={'./catalog'}>Catalog sahifa</Link> */}
        {/* </div> */}
        {children}
        <p>Footer</p>
        </body>
    </html>
  );
}
